### ISSUE TITLE
pip installation fails with error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by griddic** [oztqa/pagium#7]
macOS Catalina 10.15.4 (19E287)
Python 3.8.3

```
Collecting pagium
  Using cached pagium-0.0.15.tar.gz (6.0 kB)
    ERROR: Command errored out with exit status 1:
     command: ${PYTHON_PATH}/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7t/ztr4s4yd4_bfxbxnf_0l6rdm0000gn/T/pip-install-jen7cwfv/pagium/setup.py'"'"'; __file__='"'"'/private/var/folders/7t/ztr4s4yd4_bfxbxnf_0l6rdm0000gn/T/pip-install-jen7cwfv/pagium/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/7t/ztr4s4yd4_bfxbxnf_0l6rdm0000gn/T/pip-pip-egg-info-qcirqs7j
         cwd: /private/var/folders/7t/ztr4s4yd4_bfxbxnf_0l6rdm0000gn/T/pip-install-jen7cwfv/pagium/
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: ${PYTHON_PATH}/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7t/ztr4s4yd4_bfxbxnf_0l6rdm0000gn/T/pip-wheel-h7zk8ybj/setuptools-git-version/setup.py'"'"'; __file__='"'"'/private/var/folders/7t/ztr4s4yd4_bfxbxnf_0l6rdm0000gn/T/pip-wheel-h7zk8ybj/setuptools-git-version/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/7t/ztr4s4yd4_bfxbxnf_0l6rdm0000gn/T/pip-wheel-e26wawku
           cwd: /private/var/folders/7t/ztr4s4yd4_bfxbxnf_0l6rdm0000gn/T/pip-wheel-h7zk8ybj/setuptools-git-version/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for setuptools-git-version
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "${PYTHON_PATH}/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['${PYTHON_PATH}/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/7t/ztr4s4yd4_bfxbxnf_0l6rdm0000gn/T/tmpxg_w85x4', '--quiet', 'setuptools-git-version']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7t/ztr4s4yd4_bfxbxnf_0l6rdm0000gn/T/pip-install-jen7cwfv/pagium/setup.py", line 7, in <module>
        setup(
      File "${PYTHON_PATH}/lib/python3.8/site-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "${PYTHON_PATH}/lib/python3.8/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "${PYTHON_PATH}/lib/python3.8/site-packages/setuptools/dist.py", line 695, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "${PYTHON_PATH}/lib/python3.8/site-packages/pkg_resources/__init__.py", line 781, in resolve
        dist = best[req.key] = env.best_match(
      File "${PYTHON_PATH}/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "${PYTHON_PATH}/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "${PYTHON_PATH}/lib/python3.8/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "${PYTHON_PATH}/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['${PYTHON_PATH}/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/7t/ztr4s4yd4_bfxbxnf_0l6rdm0000gn/T/tmpxg_w85x4', '--quiet', 'setuptools-git-version']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by griddic** [comment]
workaround: run `pip install wheel` prior to install pagium

**Comment by griddic** [comment]
At this moment I can't reproduce it neither locally nor via docker.
